# Generated by Django 4.1.3 on 2022-11-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='otp',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
